name: Helm Chart

on:
  pull_request:
    paths:
      - "charts/**"
      - ".github/workflows/helm-chart.yml"

jobs:
  ci-lint-helm-charts:
    runs-on: ubuntu-latest
    steps:
      - name: ci-lint-helm-charts
        uses: smartcontractkit/.github/actions/ci-lint-charts@1bc7ce34fa81fffcb4a6eb0e4e12e59d94d0fc8f # ci-lint-charts@0.2.0
        with:
          # chart testing inputs
          chart-testing-extra-args: "--lint-conf=lintconf.yaml"
          charts-dir: charts/chainlink-cluster
          # grafana inputs
          metrics-job-name: ci-lint-helm-charts
          gc-basic-auth: ${{ secrets.GRAFANA_INTERNAL_BASIC_AUTH }}
          gc-host: ${{ secrets.GRAFANA_INTERNAL_HOST }}
          gc-org-id: ${{ secrets.GRAFANA_INTERNAL_TENANT_ID }}

  ci-kubeconform:
    runs-on: ubuntu-latest
    steps:
      - name: ci-kubeconform
        uses: smartcontractkit/.github/actions/ci-kubeconform@1bc7ce34fa81fffcb4a6eb0e4e12e59d94d0fc8f # ci-kubeconform@0.2.0
        with:
          # kubeform inputs
          charts-dir: charts/chainlink-cluster
          # grafana inputs
          metrics-job-name: ci-kubeconform
          gc-basic-auth: ${{ secrets.GRAFANA_INTERNAL_BASIC_AUTH }}
          gc-host: ${{ secrets.GRAFANA_INTERNAL_HOST }}
          gc-org-id: ${{ secrets.GRAFANA_INTERNAL_TENANT_ID }}
